// import drinkingBirdWithLight from './drinking-bird-light'
// import headLight from './head-light'
// import spotLight from './spot-light'
// import shadow from './shadow'
import swivelLightControl from './swive-light-control'